alias:
- 72b
engine_config:
  max_model_len: 8192
  model: Qwen/Qwen2.5-72B-Instruct-AWQ
project: vllm-chat
service_config:
  name: qwen2.5
  resources:
    gpu: 1
    gpu_type: nvidia-a100-80gb
  traffic:
    timeout: 300
