alias:
- 8b
engine_config:
  max_model_len: 8192
  model: NousResearch/DeepHermes-3-Llama-3-8B-Preview
project: vllm-chat
reasoning: true
server_config:
  tool_call_parser: pythonic
service_config:
  name: hermes
  resources:
    gpu: 1
    gpu_type: nvidia-a100-80gb
  traffic:
    timeout: 300
