engine_config:
  dtype: half
  max_model_len: 2048
  model: Qwen/Qwen2-1.5B-Instruct
extra_labels:
  model_name: Qwen/Qwen2-1.5B-Instruct
  openllm_alias: 1.5b,1.5b-instruct
project: vllm-chat
service_config:
  name: qwen2
  resources:
    gpu: 1
    gpu_type: nvidia-rtx-3060
  traffic:
    timeout: 300
