alias:
- 32b
engine_config:
  max_model_len: 2048
  model: Qwen/Qwen2.5-32B-Instruct
project: vllm-chat
service_config:
  name: qwen2.5
  resources:
    gpu: 1
    gpu_type: nvidia-a100-80gb
  traffic:
    timeout: 300
