engine_config:
  dtype: half
  max_model_len: 2048
  model: Qwen/Qwen2.5-32B-Instruct
extra_labels:
  model_name: Qwen/Qwen2.5-32B-Instruct
  openllm_alias: 32b,32b-instruct
project: vllm-chat
service_config:
  name: qwen2.5
  resources:
    gpu: 1
    gpu_type: nvidia-a100-80gb
  traffic:
    timeout: 300
